### ISSUE TITLE
deadlock: could not acquire callback lock

### ISSUE THREAD

**Issue by yaa110** [thibaultcha/lua-resty-mlcache#117]
I got lots of following warning:

```
[warn] 28798#28798: *28921226 [lua] mlcache.lua:740: get(): could not acquire callback lock: timeout
```

The worker that raises the warnings, stops accepting new connections (blocks forever).

- strace shows the deadlock

```bash
# strace -fs 100 -p <PID>
[pid 19819] futex(0x561dca1cd7e0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 19817] futex(0x561dca1cd7e0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
[pid 19816] futex(0x561dca1cd7e0, FUTEX_WAIT_PRIVATE, 0, NULL <unfinished ...>
...
```

- Accept queue is full for that worker.

```bash
# ss -tlpn
LISTEN 65537 65536 0.0.0.0:443 0.0.0.0:* users:(("nginx",pid=PID,fd=83),("nginx",pid=MASTER,fd=83))
```

## Environment

- Ubuntu: bionic (18.04)
- Openresty: 1.21.4.1
- mlcache: 2.6.0
- lrucache: 0.13

**Comment by thibaultcha** [comment]
It sounds like a callback is doing I/O that is taking a very long time, perhaps timing out. Then another Lua threads also needs the callback (the same key is being retrieved), and it's waiting on the first callback instead of duplicating callback calls, which is a feature of this library. I would investigate why your L3 function is timing out, which only you can debug depending on what you do in it. I would also adjust the timeout value of all I/O done within the L3 callback to be shorter than the resty-lock (see the `resty_lock_opts` option).
