### ISSUE TITLE
What's the difference between kong.mlcache and lua-resty-mlcache?

### ISSUE THREAD

**Issue by blry** [thibaultcha/lua-resty-mlcache#47]
I took a look at the source code and found that FFI is removed.

Could you please describe what side effects does it give?

**Comment by thibaultcha** [comment]
In Kong, we needed mlcache to integrate with [lua-resty-worker-events](https://github.com/Kong/lua-resty-worker-events), but this library did not support it natively when it was first written. So as of Kong 0.13.0, we ship a modified lua-resty-mlcache which supports worker-events for IPC invalidation events:

https://github.com/Kong/kong/blob/master/kong/mlcache.lua#L170-L180

This was version 1.0.0 or 1.0.1 of this library, more or less. Since then, mlcache has received many improvements that we want to benefit from in Kong. The plan was always to natively support worker-events so that we could remove the copy of mlcache in Kong, and depend on this library instead. That has been made possible since version 2.0.0 of this library. 

The next major version of Kong will ship with a dependency on this library, the change has already been merged:

https://github.com/Kong/kong/pull/3341

**Comment by thibaultcha** [comment]
Closing this now, I think it answered your question :) Thanks for your interest!
