### ISSUE TITLE
Negative TTL doesn't work when callback return nil+err

### ISSUE THREAD

**Issue by guanglinlv** [thibaultcha/lua-resty-mlcache#82]
Hi

Thanks for the best multi-level cache in the openresty world. 

There is a little confusion on negative cache, we only treat `not found` as a negative cache. should we also considering the failure of the callback without stale?

**Comment by thibaultcha** [comment]
Hi,

Thanks!

This behavior is intentional. I can however understand how the behavior you described could be desired (e.g. when the callback opened a connection that timed-out and you wish to not retry until `neg_ttl` is reached). Imho, this is the type of use-case that warrants the development of retry policies (something that has been on my mind for this library, but not anywhere near-term).

For the time being, if that is the behavior you are after, how about returning `nil, nil` and logging such errors from the callback itself?

Or do you have another reason for such a change?

**Comment by thibaultcha** [comment]
Sorry for the delay, I missed the notification for this issue. Don't hesitate to ping again in the future.
