### ISSUE TITLE
Documentation and examples for ipc and ipc_shm

### ISSUE THREAD

**Issue by stech4** [thibaultcha/lua-resty-mlcache#90]
Could anyone provide an example of how ipc_shm can be used. I created a lua_shared_dict for it but I get the below error when trying to run the docker container.

mlcache.lua:281: module 'resty.mlcache.ipc' not found:No LuaRocks module found for resty.mlcache.ipc
	no field package.preload['resty.mlcache.ipc']
	no file './resty/mlcache/ipc.lua'
	no file './resty/mlcache/ipc/init.lua'

**Comment by thibaultcha** [comment]
Hi,

Sorry for the delay on my side, I missed this issue. In the future, please don't hesitate to ping.

It seems that you did not include the `lib/resty/mlcache/ipc.lua` file which is a part of this project? The error is quite explicit. 

The `ipc_shm` option is documented under the [new()](https://github.com/thibaultcha/lua-resty-mlcache#new) method and an example is included in this section as well. You can also browse this project's extensive test suite for more examples.

There is a note regarding the `ipc` option in the [update](https://github.com/thibaultcha/lua-resty-mlcache#update) method's documentation, but I highly discourage you from playing with it unless you really know what you are doing (it is not documented for a reason, because the bundled IPC mechanism is probably enough for your use-case).
